# Generated by Django 4.2 on 2023-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_employees_email_alter_employees_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]   
