# Generated by Django 3.2.12 on 2023-05-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_employees_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.TextField(),
        ),
    ]
